export {
  CREDENTIAL_LANES,
  ConnectionError,
  PROVIDER_LANES,
  connect,
  connectWithKey,
  connectWithToken,
  connectionHealth,
  isOAuthSource,
  isSelfIssued,
  lanesFor,
  offersLane,
  openCredential,
  recordFailure,
  type ConnectionHealth,
  type ConnectionProvider,
  type ConnectionRow,
  type ConnectionStatus,
  type ConnectionStore,
  type CredentialLane,
  type StoredCredential,
} from "./connections.js";
